import React from 'react';
import { MobilityState } from '../../lib/mobility/types';
import { Zap } from 'lucide-react';

interface IntelligencePanelProps {
  mobilityState: MobilityState;
}

export default function IntelligencePanel({ mobilityState }: IntelligencePanelProps) {
  // We use the deterministic explanation generated by the ScenarioEngine
  return (
    <div className="bg-gradient-to-br from-indigo-900/40 to-purple-900/20 border border-indigo-500/30 rounded-xl p-5 shadow-lg relative overflow-hidden">
      <div className="absolute top-0 left-0 w-1 h-full bg-indigo-500"></div>
      
      <div className="flex items-center mb-3">
        <Zap className="w-5 h-5 text-indigo-400 mr-2" />
        <h3 className="text-indigo-300 text-xs font-bold uppercase tracking-widest">Mobility Intelligence</h3>
      </div>
      
      <p className="text-gray-200 text-lg leading-snug">
        {mobilityState.explanation || 'Initializing intelligence engine...'}
      </p>

      {mobilityState.scenarioState === 'HOTSPOT_FORMED' && (
        <div className="mt-4 flex space-x-2">
          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-900/50 text-red-300 border border-red-800">
            Evaluating alternatives
          </span>
          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-orange-900/50 text-orange-300 border border-orange-800">
            Scoring costs
          </span>
        </div>
      )}
    </div>
  );
}
